name: CI

on: [push, pull_request]

env:
  DEVELOPER: 1

jobs:
  windows-meson-build:
    name: win+Meson build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Set up dependencies
      shell: pwsh
      run: pip install meson ninja
    - name: Setup
      shell: pwsh
      run: meson setup build --vsenv -Dbuildtype=release -Dperl=disabled -Dcredential_helpers=wincred
    - name: Compile
      shell: pwsh
      run: meson compile -C build
    - name: Test
      shell: bash
      timeout-minutes: 5
      run: meson test -C build t5410-receive-pack -i --test-args=-x
